# Generated by Django 4.1.7 on 2023-04-07 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='comments/')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='comments.comment')),
            ],
        ),
    ]
