# Generated by Django 4.1.7 on 2023-04-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientquantity',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
